(define (emit-program x)
  (unless (integer? x) (error ---))
  (emit " .text")
  (emit " .globl scheme_entry")
  (emit " .type scheme_entry, @function")
  (emit "scheme_entry:")
  (emit " movl $~s, %eax" (fxsll x 2))
  (emit " ret")
  (emit ".section   .note.GNU-stack,\"\",@progbits")
  )
